# version: 1.1.0
"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
continuation_prompt = "[▸▹ ](#7679A7)"

format = """($nix_shell$container$fill$git_metrics\n)$cmd_duration\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$character"""

right_format = """
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cpp\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$fortran\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$xmake\
$zig\
$buf\
$conda\
$pixi\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$status\
$os\
$battery\
$time"""

[fill]
symbol = " "

[character]
format = "$symbol "
success_symbol = "[◎ ](bold italic #EAA041)"
error_symbol = "[○ ](italic #E16765)"
vimcmd_symbol = "[■ ](italic #46A3AF)"
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□ "
vimcmd_visual_symbol = "▼ "

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = "#46A3AF italic"

[sudo]
format = "[$symbol]($style)"
style = "bold italic #c678dd"
symbol = "⋈┈"
disabled = false

[username]
style_user = "#c678dd bold italic"
style_root = "#c678dd bold italic"
format = "[⭘ $user]($style) "
disabled = false
show_always = false

[directory]
home_symbol = "⌂"
truncation_length = 2
truncation_symbol = "□ "
read_only = " ◈"
use_os_path_sep = true
style = "italic #46A3AF"
format = "[$path]($style)[$read_only]($read_only_style)"
repo_root_style = "bold #46A3AF"
repo_root_format = "[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [△ ](bold #46A3AF)"

[cmd_duration]
format = "[◄ $duration ](italic #7679A7)"

[jobs]
format = "[$symbol$number]($style) "
style = "#B4B7CF"
symbol = "[▶ ](#46A3AF italic)"

[localip]
ssh_only = true
format = " ◯ [$localipv4](bold #c678dd)"
disabled = false

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "italic #7679A7"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "█"
charging_symbol = "[↑](italic bold #46A3AF)"
discharging_symbol = "↓"
unknown_symbol = "░"
empty_symbol = "▃"

[[battery.display]]
threshold = 20
style = "italic bold #E16765"

[[battery.display]]
threshold = 60
style = "italic #c678dd"

[[battery.display]]
threshold = 70
style = "italic #EAA041"

[git_branch]
format = " [$branch(:$remote_branch)]($style)"
symbol = "[△ ](bold italic #46A3AF)"
style = "italic #46A3AF"
truncation_symbol = "⋯ "
truncation_length = 11
ignore_branches = ["main", "master"]
only_attached = true

[git_metrics]
format = "([▴ $added]($added_style))([▿ $deleted]($deleted_style))"
added_style = "italic #46A3AF"
deleted_style = "italic #E16765"
ignore_submodules = true
disabled = false

[git_status]
style = "bold italic #46A3AF"
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"
conflicted = "[◪ ◦](italic #c678dd)"
ahead = "[▴ │[${count}](bold #B4B7CF)│](italic #46A3AF)"
behind = "[▿ │[${count}](bold #B4B7CF)│](italic #E16765)"
diverged = "[◇ ▴ ┤[${ahead_count}](regular #B4B7CF)│▿┤[${behind_count}](regular #B4B7CF)│](italic #c678dd)"
untracked = "[◌◦](italic #c678dd)"
stashed = "[◃◈ ](italic #7679A7)"
modified = "[● ◦](italic #EAA041)"
staged = "[▪ ┤[$count](bold #B4B7CF)│](italic #46A3AF)"
renamed = "[◎ ◦](italic #c678dd)"
deleted = "[✕](italic #E16765)"

# --- Language Modules ---

[deno]
format = " [deno](italic) [∫ $version](#46A3AF bold)"

[lua]
format = " [lua](italic) [${symbol}${version}]($style)"
symbol = "⨀ "
style = "bold #c678dd"

[nodejs]
format = " [node](italic) [◫ ($version)](bold #46A3AF)"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]

[python]
format = " [py](italic) [${symbol}${version}]($style)"
symbol = "[⌉](bold #46A3AF)⌊ "
style = "bold #c678dd"

[ruby]
format = " [rb](italic) [${symbol}${version}]($style)"
symbol = "◆ "
style = "bold #E16765"

[rust]
format = " [rs](italic) [$symbol$version]($style)"
symbol = "⊃ "
style = "bold #E16765"

[package]
format = " [pkg](italic #7679A7) [$symbol$version]($style)"
symbol = "◨ "
style = "#c678dd italic bold"

[swift]
format = " [sw](italic) [${symbol}${version}]($style)"
symbol = "◁ "
style = "bold #E16765"

[aws]
disabled = true
format = " [aws](italic) [$symbol $profile $region]($style)"
style = "bold #46A3AF"
symbol = "▲ "

[buf]
symbol = "■ "
format = " [buf](italic) [$symbol $version $buf_version]($style)"

[c]
symbol = "ℂ "
format = " [$symbol($version(-$name))]($style)"
style = "bold #46A3AF"

[cpp]
symbol = "ℂ "
format = " [$symbol($version(-$name))]($style)"
style = "bold #46A3AF"

[conda]
symbol = "◯ "
format = " conda [$symbol$environment]($style)"

[pixi]
symbol = "■ "
format = " pixi [$symbol$version ($environment )]($style)"

[dart]
symbol = "◁◅ "
format = " dart [$symbol($version )]($style)"

[docker_context]
symbol = "◧ "
format = " docker [$symbol$context]($style)"
style = "bold #46A3AF"

[elixir]
symbol = "△ "
format = " exs [$symbol $version OTP $otp_version ]($style)"
style = "bold #c678dd"

[elm]
symbol = "◩ "
format = " elm [$symbol($version )]($style)"

[golang]
symbol = "∩ "
format = " go [$symbol($version )]($style)"
style = "bold #46A3AF"

[haskell]
symbol = "❯λ "
format = " hs [$symbol($version )]($style)"

[java]
symbol = "∪ "
format = " java [${symbol}(${version} )]($style)"

[julia]
symbol = "◎ "
format = " jl [$symbol($version )]($style)"

[memory_usage]
symbol = "▪▫▪ "
format = " mem [${ram}( ${swap})]($style)"
style = "#7679A7"

[nim]
symbol = "▴▲▴ "
format = " nim [$symbol($version )]($style)"

[nix_shell]
style = "bold italic #7679A7"
symbol = "✶"
format = "[$symbol nix⎪$state⎪]($style) [$name](italic #B4B7CF)"
impure_msg = "[⌽](bold #E16765)"
pure_msg = "[⌾](bold #46A3AF)"
unknown_msg = "[◌](bold #c678dd)"

[spack]
symbol = "◇ "
format = " spack [$symbol$environment]($style)"
