# version: 1.1.0
"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
continuation_prompt = "[│ ──> ](fg:#1E455A)"

format = """
[┌─┤](fg:#2A5A70)$nix_shell$container$jobs$sudo$cmd_duration[├─](fg:#2A5A70)$fill$git_metrics[│](fg:#2A5A70)
[└─┤](fg:#2A5A70)$username$hostname$localip$directory[├─>](fg:#2A5A70)$character"""

right_format = """
[┤](fg:#2A5A70)$git_branch$git_state$git_status[├─┤](fg:#2A5A70)\
$python$lua$nodejs$rust$c$cpp$package$memory_usage$battery[├─┐](fg:#2A5A70)"""

[fill]
symbol = "─"
style = "fg:#143040"

[character]
format = "$symbol"
success_symbol = "[ ▰ ](fg:#7EE6F2)"
error_symbol = "[ ▱ ](fg:#FF99AA)"
vimcmd_symbol = "[ ■ ](fg:#88FF99)"
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[username]
style_user = "fg:#F0CD66 bold"
style_root = "fg:#FF99AA bold"
format = "[$user ](style)"
disabled = false
show_always = true

[hostname]
style = "fg:#2A5A70"
format = "[@$hostname](style) "
disabled = false

[directory]
home_symbol = "SCTR_0"
truncation_length = 1
truncation_symbol = "…/"
read_only = " [🔒]"
use_os_path_sep = true
style = "fg:#88EEFF bold"
format = "in [$path]($style)[$read_only](fg:#FF99AA)"
repo_root_style = "bold fg:#7EE6F2"
repo_root_format = "in [$repo_root]($repo_root_style)/[$path]($style)"

[cmd_duration]
format = "[│ LOG_TIM: $duration ](fg:#2A5A70)"

[jobs]
format = "[│ JOBS: $number ]($style)"
style = "fg:#F0CD66"

[localip]
ssh_only = true
format = "[│ REM_ACC: $localipv4 ](fg:#FF99AA)"
disabled = false

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
style = "fg:#2A5A70"

[battery]
format = " [BAT:$percentage]($style)"
full_symbol = ""
charging_symbol = "↑"
discharging_symbol = "↓"

[[battery.display]]
threshold = 20
style = "fg:#FF99AA bold"

[[battery.display]]
threshold = 100
style = "fg:#2A5A70"

[git_branch]
format = "[ FILE: $branch ]($style)"
style = "fg:#88EEFF bold"
symbol = ""

[git_metrics]
format = "[BATCH INTEGRITY: ](fg:#2A5A70)[+$added](fg:#88FF99)/[-$deleted](fg:#FF99AA) "
ignore_submodules = true
disabled = false

[git_status]
style = "fg:#7EE6F2"
format = "([│ $ahead_behind$staged$modified$untracked$deleted$conflicted ⎥]($style))"
conflicted = "[CRIT](fg:#FF99AA) "
ahead = "[▲ $count](fg:#88FF99) "
behind = "[▼ $count](fg:#FF99AA) "
untracked = "[RAW](fg:#F0CD66) "
modified = "[MOD](fg:#F0CD66) "
staged = "[STG](fg:#7EE6F2) "
deleted = "[DEL](fg:#FF99AA) "

[python]
format = "[│ PY:$version ]($style)"
style = "fg:#2A5A70"

[lua]
format = "[│ LUA:$version ]($style)"
style = "fg:#2A5A70"

[nodejs]
format = "[│ NODE:$version ]($style)"
style = "fg:#2A5A70"

[rust]
format = "[│ RS:$version ]($style)"
style = "fg:#2A5A70"

[c]
format = "[│ C:$version ]($style)"
style = "fg:#2A5A70"

[cpp]
format = "[│ CPP:$version ]($style)"
style = "fg:#2A5A70"

[package]
format = "[│ PKG:$version ]($style)"
style = "fg:#1E455A"

[nix_shell]
style = "fg:#88EEFF"
format = "[NIX: $state ]($style)"
impure_msg = "IMPURE"
pure_msg = "COMPLIANT"
unknown_msg = "UNVERIFIED"

[memory_usage]
disabled = false
threshold = -1
style = "fg:#2A5A70"
format = "[│ MEM:$ram ]($style)"
